# Generated by Django 2.0 on 2018-03-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speakers',
            options={'verbose_name_plural': 'Speakers'},
        ),
    ]
